---
- name: Restart UniFi Controller
  community.docker.docker_compose_v2:
    project_src: /etc/unifi
    state: restarted
  become: true

- name: Reload ufw
  community.general.ufw:
    state: reloaded
