---
- name: Reconfigure GitLab
  ansible.builtin.command: gitlab-ctl reconfigure
  register: gitlab_reconfigure_handler
  changed_when: gitlab_reconfigure_handler.rc == 0

- name: Restart GitLab
  ansible.builtin.command: gitlab-ctl restart
  register: gitlab_restart_handler
  changed_when: gitlab_restart_handler.rc == 0