---
- name: Restart monitoring stack
  community.docker.docker_compose_v2:
    project_src: /etc/monitoring
    state: restarted
  become: true

- name: Reload ufw
  community.general.ufw:
    state: reloaded
