---
- name: Restart nginx
  ansible.builtin.systemd:
    name: nginx-filescdn.service
    state: restarted
    daemon_reload: yes

- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: yes

- name: Reload ufw
  community.general.ufw:
    state: reloaded
